{ config, pkgs, lib, ... }:
let
  version = "17.2.0";
  oh-my-pi = pkgs.stdenv.mkDerivation {
    pname = "oh-my-pi";
    inherit version;
    src = pkgs.fetchurl {
      url = "https://github.com/can1357/oh-my-pi/releases/download/v${version}/omp-linux-x64";
      hash = "sha256-H7eJhieiEFz5pIavgEELATlCYCemwzdG2fNz38cKOEY=";
    };
    dontUnpack = true;
    dontStrip = true;
    nativeBuildInputs = with pkgs; [ makeBinaryWrapper ];
    installPhase = ''
      runHook preInstall
      mkdir -p $out/bin
      cp $src $out/bin/omp
      chmod +x $out/bin/omp
      runHook postInstall
    '';
    postFixup = ''
      wrapProgram $out/bin/omp \
        --prefix PATH : ${lib.makeBinPath [ pkgs.ripgrep pkgs.fd ]}
    '';
    meta = {
      description = "AI coding agent for the terminal - fork of Pi with enhanced capabilities";
      homepage = "https://omp.sh";
      license = lib.licenses.mit;
      mainProgram = "omp";
      platforms = [ "x86_64-linux" ];
    };
  };

  generateOmpConfig = pkgs.writeShellApplication {
    name = "generate-omp-config";
    runtimeInputs = with pkgs; [ curl ];
    text = ''
      OMP_AGENT_DIR="$HOME/.omp/agent"
      mkdir -p "$OMP_AGENT_DIR"

      MODELS_FILE="$OMP_AGENT_DIR/models.yml"

      echo "Querying Ollama for local models..."
      OLLAMA_MODELS=""
      if curl -s -f http://localhost:11434/api/tags > /dev/null 2>&1; then
        OLLAMA_MODELS=$(curl -s http://localhost:11434/api/tags | ${pkgs.jq}/bin/jq -r '.models[].name' | while IFS= read -r model; do
          ctx=$(curl -s http://localhost:11434/api/show -d "{\"model\": \"$model\"}" | ${pkgs.jq}/bin/jq -r '((.parameters // "") | capture("num_ctx (?<n>[0-9]+)") | .n) // ""')
          if [ -z "$ctx" ]; then
            ctx=4096
          fi
          name=$(echo "$model" | sed 's/:.*//' | sed 's/-/ /g')
          echo "    - id: \"$model\""
          echo "      name: \"$name (Local)\""
          echo "      contextWindow: $ctx"
          echo "      maxTokens: $((ctx / 2))"
        done)
        if [ -n "$OLLAMA_MODELS" ]; then
          OLLAMA_MODELS=$(printf "\n%s" "$OLLAMA_MODELS")
        fi
      else
        echo "Warning: Ollama is not running."
      fi

      echo "Querying LM Studio for local models..."
      LMSTUDIO_MODELS=""
      if curl -s -f http://localhost:1234/v1/models > /dev/null 2>&1; then
        LMSTUDIO_MODELS=$(curl -s http://localhost:1234/v1/models | ${pkgs.jq}/bin/jq -r '
          [.data[] | {
            id: .id,
            name: ((.id | split(":")[0] | gsub("-"; " ")) + " (Local)"),
            contextWindow: 8192,
            maxTokens: 4096
          }] | .[] | "    - id: \"\(.id)\"\n      name: \"\(.name)\"\n      contextWindow: \(.contextWindow)\n      maxTokens: \(.maxTokens)"
        ')
        if [ -n "$LMSTUDIO_MODELS" ]; then
          LMSTUDIO_MODELS=$(printf "\n%s" "$LMSTUDIO_MODELS")
        fi
      else
        echo "Warning: LM Studio is not running."
      fi

      echo "Generating $$MODELS_FILE..."
      cat > "$MODELS_FILE" <<YAML
providers:
  ollama:
    baseUrl: http://localhost:11434/v1
    api: openai-completions
    apiKey: ollama
    models:$OLLAMA_MODELS

  lmstudio:
    baseUrl: http://localhost:1234/v1
    api: openai-completions
    apiKey: lm-studio
    models:$LMSTUDIO_MODELS

YAML
      echo "Done! Configuration saved to $$MODELS_FILE."
    '';
  };

in
{
  options = {
    dpom-oh-my-pi.enable = lib.mkEnableOption "Add oh-my-pi coding agent (omp)";
  };
  config = lib.mkIf config.dpom-oh-my-pi.enable {
    home.packages = [ oh-my-pi generateOmpConfig ];

    home.activation.generateOmpConfig = lib.hm.dag.entryAfter ["writeBoundary"] ''
      $DRY_RUN_CMD ${generateOmpConfig}/bin/generate-omp-config
    '';

    # Bash completions (when managed by home-manager)
    programs.bash.initExtra = ''
      eval "$(omp completions bash)"
    '';

    # Zsh completions (when managed by home-manager)
    programs.zsh.initExtra = ''
      eval "$(omp completions zsh)"
    '';

    # Fish completions (when managed by home-manager)
    xdg.configFile."fish/completions/omp.fish".text = ''
      # oh-my-pi completions - generated by omp
      # Installing omp completions for fish shell.
    '';

    home.activation.generateOmpCompletions = lib.hm.dag.entryAfter ["writeBoundary"] ''
      # Fish completions - regenerate from current omp binary
      FISH_COMPLETIONS_DIR="$HOME/.config/fish/completions"
      mkdir -p "$FISH_COMPLETIONS_DIR"
      ${oh-my-pi}/bin/omp completions fish > "$FISH_COMPLETIONS_DIR/omp.fish.new"
      if ! cmp -s "$FISH_COMPLETIONS_DIR/omp.fish" "$FISH_COMPLETIONS_DIR/omp.fish.new" 2>/dev/null; then
        mv "$FISH_COMPLETIONS_DIR/omp.fish.new" "$FISH_COMPLETIONS_DIR/omp.fish"
      else
        rm -f "$FISH_COMPLETIONS_DIR/omp.fish.new"
      fi
    '';
  };
}
